## 模板1
import os

env = None
# 1.编译器
if os.system("which clang"):
    env = Environment()
else:
    # clang编译器
    env = Environment(tools=["default", "clang"])
    env["CC"] = ["clang"]
    env["CXX"] = ["clang++"]

env["PROGSUFFIX"] = ".out"            # 可执行后缀.out
env["CCFLAGS"] = " -ggdb3 -O0 -Wall"  # gdb 调试开关

env.MergeFlags(
    [
        "!pkg-config --cflags --libs jsoncpp",
    ]
)
src_list = [
    "1_jsonCpp_解析字符串_增.删.改.查.保存.cc",
    "2_jsonCpp_从文件读取.cc",
]
for src in src_list:
    env.Program(Split(src))
