## 模板1
import os

env = None
# 1.编译器
if os.system("which clang"):
    env = Environment()
else:
    # clang编译器
    env = Environment(tools=["default", "clang"])
    env["CC"] = ["clang"]
    env["CXX"] = ["clang++"]

env["PROGSUFFIX"] = ".out"            # 可执行后缀.out
env["CCFLAGS"] = " -ggdb3 -O0 -Wall"  # gdb 调试开关
src_list = [
    "1_rvalue-references-move-semantics_右值引用_移动赋值.cc",
    "5_copy_constructor拷贝构造.cc",
    "6_copy_constructor_无拷贝构造_1次构造_2次析构_异常现象.cc",
]
for src in src_list:
    env.Program(Split(src))
