## 模板1
import os

env = None
# 1.编译器
if os.system("which clang"):
    env = Environment()
else:
    # clang编译器
    env = Environment(tools=["default", "clang"])
    env["CC"] = ["clang"]
    env["CXX"] = ["clang++"]

env["PROGSUFFIX"] = ".out"            # 可执行后缀.out
env["CCFLAGS"] = " -ggdb3 -O0 -Wall"  # gdb 调试开关
src_list = [
    "1_无虚函数-重写.cpp",
    "1.1_有虚函数_重写.cpp",
    "2_纯虚函数类-实例化失败.cpp",
]
for src in src_list:
    env.Program(Split(src))
