## 模板1
import os

env = None
# 1.编译器
if os.system("which clang"):
    env = Environment()
else:
    # clang编译器
    env = Environment(tools=["default", "clang"])
    env["CC"] = ["clang"]
    env["CXX"] = ["clang++"]

env["PROGSUFFIX"] = ".out"              # 可执行文件后缀.out
env["CCFLAGS"] = " -g3 -O0"       # gdb 调试
src_list = [
    "11_static_cast_强制类型转化.cc",
    "21_dynamic_cast_子类强制指向父类.cc",
    "31_const_cast_常量转变量.cc",
    "41_reinterpret_cast_void指针任意类型转化.cc",
]
for src in src_list:
    env.Program(Split(src))
