## 模板1
import os

env = None
# 1.编译器
if os.system("which clang"):
    env = Environment()
else:
    # clang编译器
    env = Environment(tools=["default", "clang"])
    env["CC"] = ["clang"]
    env["CXX"] = ["clang++"]

env["PROGSUFFIX"] = ".out"            # 可执行后缀.out
env["CCFLAGS"] = " -ggdb3 -O0 -Wall"  # gdb 调试开关
src_list = [
    "1_crc16_xmodem.c",
    "2_crc16_大文件计算.c"
]
for src in src_list:
    env.Program(Split(src))


# 生成大文件
target_file = "test.img"
if os.path.exists(target_file) == False:
    print(f"生成大文件 {target_file}")
    os.system(f"dd if=/dev/random of={target_file} bs=1M count=1024")
