import os
def gen_exec_file(file):
    return os.path.splitext(file)[0]+'.out'

# clang编译器
env = Environment(tools = ['default', 'clang'])
env['CC']=['clang']
env['CXX']=['clang++']
env['CCFLAGS'] = '-ggdb3 -O0 -Wall'

def build_out(src_file):
    src = Split(src_file)
    target = gen_exec_file(src[0])
    env.Program(target, src)

build_out('1_引用作为参数.cpp')
build_out('2_返回引用.cpp')
build_out('3_类-引用成员初始化.cc')