## 模板1
import os

env = None
# 1.编译器
if os.system("which clang"):
    env = Environment()
else:
    # clang编译器
    env = Environment(tools=["default", "clang"])
    env["CC"] = ["clang"]
    env["CXX"] = ["clang++"]

env["PROGSUFFIX"] = ".out"  # 可执行后缀.out
env["CCFLAGS"] = " -ggdb3 -O0 -Wall"  # gdb 调试开关
src_list = [
    "1_引用作为参数.cpp",
    "2_引用参数_返回引用.cpp",
    "3_类-引用成员初始化.cc",
    "4_指针转引用.cc",
]
for src in src_list:
    env.Program(Split(src))
