import os

env = None
# 1.编译器
if os.system("which clang"):
    env = Environment()
else:
    # clang编译器
    env = Environment(tools=["default", "clang"])
    env["CC"] = ["clang"]
    env["CXX"] = ["clang++"]

env["PROGSUFFIX"] = ".out"  # 可执行后缀.out
env["CCFLAGS"] = " -ggdb3 -O0 "  # gdb 调试开关

env["LIBS"] = ["glib-2.0", "pthread"]
env.MergeFlags(
    [
        "!pkg-config dbus-1 --cflags --libs",
        "!pkg-config dbus-glib-1 --cflags --libs",
        "!pkg-config gio-2.0 --cflags --libs",
    ]
)
src_list = [
    "dbus-client.c","dbus-server.c",
]

for src in src_list:
    env.Program(Split(src))
